#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
#!!!!!!!! DO NOT EDIT THIS FILE !!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
#
# Please create a file called ~/.my_shell_stuff and put your 
# speficic aliases/exports/functions/whatever there. Let's 
# keep this file simple!

## Useful variables
# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh_history

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# For some themes which cursor is underline, when exit vim the cursor becomes a box. This function
# fix this error
_fix_cursor() {
  echo -ne '\e[3 q'
}
precmd_functions+=(_fix_cursor)
# Complements
# You may want to put all your additions into a separate file like
# ~/.my_zsh_complements, instead of adding them here directly.
if [ -f $HOME/.my_shell_stuff ]; then
   . $HOME/.my_shell_stuff
fi
# add general aliases
source "$HOME/.aliases"
test alias f5 > /dev/null 2>&1 || alias f5='source $HOME/.zshrc'
##
# OTHER USEFUL STUFF... OR NOT...
##
#
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# load starship
eval "$(starship init zsh)"
